# Generated by Django 5.2.6 on 2026-01-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-start_time'], 'permissions': [('view_all_mailings', 'Can view all mailings'), ('block_mailing', 'Can block mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
